### PR TITLE
Fix discrepancy with Sbt plugin by passing the dependency classpath to Scalafix

### LINKED ISSUE #30: Option to specify scalafix version number
Would be nice not to depend upon plugin to set the scalafix dependency version.

It would be nice if a property is exposed for this

### PR DESCRIPTION
**Pull request by marcelocenerine**
Fixes #30

### CODE REVIEW

File: src/compatTest/groovy/io/github/cosmicsilence/scalafix/ScalafixPluginFunctionalTest.groovy [hunk 1]
```diff
@@ -279,18 +281,22 @@ No Scalafix rules to run'''
...
 
         when:
         runGradle(projectDir, 'scalafix')
 
         then:
         src.getText() == '''
-object HelloWorld
+object HelloWorld {
+  def foo: Map[Int,String] = Map(1 -> "one")
+}
```
Comment (marcelocenerine) [inline src/compatTest/groovy/io/github/cosmicsilence/scalafix/ScalafixPluginFunctionalTest.groovy:299]: https://github.com/jahan01/opensource-issues/blob/master/scalafix_organize_imports/src/main/scala/myfile2.scala

File: src/compatTest/groovy/io/github/cosmicsilence/scalafix/ScalafixPluginFunctionalTest.groovy [hunk 2]
```diff
@@ -730,43 +789,55 @@ DisableSyntax.noVars = true
...
 import scala.concurrent.duration._
 
-sealed trait Animal
-final case class Dog(breed: String) extends Animal
-final case class Cat(breed: String) extends Animal
+import sun.misc.Unsafe
+
+import scala.language.postfixOps
+
+object Foo
```
Comment (marcelocenerine) [inline src/compatTest/groovy/io/github/cosmicsilence/scalafix/ScalafixPluginFunctionalTest.groovy:832]: https://github.com/jahan01/opensource-issues/blob/master/scalafix_organize_imports/src/main/scala/myfile1.scala

File: src/main/groovy/io/github/cosmicsilence/scalafix/ScalaSourceSet.groovy [hunk 3]
```diff
@@ -20,8 +20,8 @@ class ScalaSourceSet {
         return sourceSet.name
     }
 
-    List<File> getClassesDirs() {
-        return sourceSet.output.classesDirs.toList()
+    List<File> getFullClasspath() {
+        return (sourceSet.output.classesDirs + sourceSet.compileClasspath).toList()
```
Comment (marcelocenerine) [inline src/main/groovy/io/github/cosmicsilence/scalafix/ScalaSourceSet.groovy:24]: the plugin was not including the dependencies (jars) in the classpath passed to Scalafix.

File: src/main/groovy/io/github/cosmicsilence/scalafix/ScalafixTask.groovy [hunk 4]
```diff
@@ -65,36 +71,47 @@ class ScalafixTask extends SourceTask {
...
 
+    private void assertSemanticdbIsConfigured(List<ScalafixRule> rulesThatWillRun) {
+        def semanticRules = rulesThatWillRun.findAll { it.kind().isSemantic() }
+
+        if (!semanticRules.empty && !semanticdbConfigured) {
+            def semanticRuleNames = semanticRules.collect { it.name() }.join(", ")
+            throw new GradleException("The semanticdb compiler plugin is required to run semantic rules such as ${semanticRuleNames}. " +
+                    "To fix this problem, please enable 'autoConfigureSemanticdb' in the scalafix plugin extension")
+        }
+    }
```
Comment (marcelocenerine) [inline src/main/groovy/io/github/cosmicsilence/scalafix/ScalafixTask.groovy:113]: as a side effect of including the dependency jars in the classpath passed to Scalafix is that the latter no longer reports a `ScalafixError.MissingSemanticdbError` when running semantic rules without having the Semanticdb files generated by the compiler plugin. The `sbt-scalafix` plugin performs some [upfront validation](https://github.com/scalacenter/sbt-scalafix/blob/master/src/main/scala/scalafix/internal/sbt/SemanticRuleValidator.scala#L18-L19) like I'm doing now ☝️ . I managed to bypass the Sbt plugin validation by adding `semanticdb-scalac` as a dependency of the project and got the same result: no `ScalafixError.MissingSemanticdbError` is reported.
